### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by JayJoshi802**
Added links to the Widget,Media,Social Media,Blog,Menu and Contact info.

### CODE REVIEW

**Comment by Tinkusingh0803** [comment]
I have merged your update

**Review by Tinkusingh0803 — COMMENTED** [review]
good work

**Comment by JayJoshi802** [comment]
> good work

Thank You!!

**Comment by JayJoshi802** [comment]
I am new to GitHub and I am still learning how to use Git and GitHub

**Comment by Tinkusingh0803** [comment]
i know you are new on github

**Pull request merged**
